name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - name: Test GitHub token
        env:
          GH_STATS_TOKEN: ${{ secrets.GH_STATS_TOKEN }}
        run: |
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Authorization: Bearer $GH_STATS_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2026-03-10" \
            https://api.github.com/user)
      
          echo "GitHub API status: $STATUS"
      
          if [ "$STATUS" != "200" ]; then
            echo "Token não está sendo aceito pelo GitHub."
            exit 1
          fi
  
          echo "Token autenticado com sucesso!"

      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install requests
        run: |
          pip install requests

      - name: Check files
        run: |
          echo "Diretório atual:"
          pwd

          echo ""
          echo "Arquivos .github:"
          find .github -maxdepth 3 -type f -print

      - name: Generate languages card
        env:
          GH_STATS_TOKEN: ${{ secrets.GH_STATS_TOKEN }}
          GITHUB_USERNAME: ${{ github.repository_owner }}
        run: |
          python scripts/generate_languages.py

      - name: Commit SVG
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add profile/top-langs-all.svg

          git commit -m "Update private languages stats" || exit 0

          git push
